function x(t) return t; end
function f()
  local tt: integer[] = {1}
  local ss: number[] = { 55.5 }
  tt = x(tt)
  ss = x(ss)
end
assert(ravi.compile(x))
assert(ravi.compile(f))
ravi.dumpllvm(x)
ravi.dumpllvm(f)
assert(pcall(f))
function f()
  local tt: integer[] = {1}
  tt = x({})
end
ravi.dumplua(f)
assert(ravi.compile(f))
ravi.dumpllvm(f)
-- Following causes a misaligned stack exception
assert(not pcall(f))
print("test OK")